config/routes.rb
Blog::Application.routes.draw do
  
  
  resources :projects
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :link, :name, :description
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password_digest
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end
  
  def new
    @project = Project.new
  end
  
  def create
    @project = Project.new(params[:project])
    binding.pry
    if @project.save
      redirect_to projects_path
    else
      render "new"
    end
  end
  
  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path
  end
  
  def edit
    @project = Project.find(params[:id])
  end
  
  def show
    @project = Project.find(params[:id])
  end
  
  def update
    @project = Project.find(params[:id])

    if @project.update_attributes(params[:project])
      redirect_to project_path(@project.id)
    else
      render "edit"
    end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/edit.html.erb
<h1>Edit Project Info</h1>

<%= form_for(@project) do |p| %>

  <p>
    <%= p.label :name %>
    <%= p.text_field :name %>
  </p>
  
  <p>
    <%= p.label :link %>
    <%= p.text_field :link %>
  </p>
  
  <p>
    <%= p.label :description %>
    <%= p.text_area :description %>
  </p>
  
  <%= p.submit %>
<% end %>

app/views/projects/index.html.erb
<h1>List of Projects</h1>

<% if @projects.empty? %>
  <p><%= "No projects listed" %></p>
<% else %>
  <% @projects.each do |a| %>
    <p>
      <%= link_to(a.name, project_path(a.id))%> | 
      <%= link_to 'Destroy', project_path(a.id), method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
  <% end %>
<% end %>


<%= link_to("Add a new Project", new_project_path) %>

app/views/projects/new.html.erb
<h1>Add a Project</h1>

<%= form_for @project do |p| %>

  <p>
    <%= p.label :name %>
    <%= p.text_field :name %>
  </p>
  
  <p>
    <%= p.label :link %>
    <%= p.text_field :link %>
  </p>
  
  <%= p.submit %>
  
<% end %>

app/views/projects/show.html.erb
<h1>Project Information</h1>



<h2><%= @project.name %></h2>

<p>
  <%= @project.description %>
</p>


<body>
  <%= link_to("Github", @project.link) %> |
  <%= link_to("Edit", edit_project_path(@project.id)) %>
</body>

<p>
  <%= link_to("Home", projects_path) %>